codecov:
  token: c7679830-5199-4b3f-bb77-fd34916c14e3

ignore:
  - "**/*.tsx"
  - "**/*.test.ts"
  - "components/*.ts"
  - "components/*.ts"
  - "helpers/*.ts"
  - "components/blockchain/*.ts"
  - "components/blockchain/**/*.ts"
  - "components/content/*.ts"
  - "helpers/icons/*.ts"
  - "helpers/loadingIndicator/*.ts"
  - "helpers/text/*.ts"
